/******************************************************************************
 * Product: Compiere ERP & CRM Smart Business Solution                        *
 * Copyright (C) 1999-2006 ComPiere, Inc. All Rights Reserved.                *
 * This program is free software; you can redistribute it and/or modify it    *
 * under the terms version 2 of the GNU General Public License as published   *
 * by the Free Software Foundation. This program is distributed in the hope   *
 * that it will be useful, but WITHOUT ANY WARRANTY; without even the implied *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
 * See the GNU General Public License for more details.                       *
 * You should have received a copy of the GNU General Public License along    *
 * with this program; if not, write to the Free Software Foundation, Inc.,    *
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.                     *
 * For the text or an alternative of this public license, you may reach us    *
 * ComPiere, Inc., 2620 Augustine Dr. #245, Santa Clara, CA 95054, USA        *
 * or via info@compiere.org or http://www.compiere.org/license.html           *
 *****************************************************************************/

package org.compiere.jsf.backing;

import org.apache.myfaces.custom.tree2.HtmlTree;
import org.apache.myfaces.custom.tree2.TreeNode;
import org.apache.myfaces.custom.tree2.TreeNodeBase;
import org.apache.myfaces.custom.tree2.TreeModel;
import org.apache.myfaces.custom.tree2.TreeModelBase;
import org.compiere.model.MTree;
import org.compiere.model.MTreeNode;
import org.compiere.util.CLogger;
import org.compiere.util.DB;
import org.compiere.util.Env;

import javax.faces.context.FacesContext;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIParameter;
import javax.faces.validator.ValidatorException;
import javax.faces.event.ActionEvent;

import java.io.Serializable;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

public class TreeBacker implements Serializable
{
	private static final long serialVersionUID = 3599561508963145896L;
	/**   The HTML tree generated by the tree2 component  */
	private HtmlTree _tree;
	/**   Holds id of tree created                        */  
	private int treeId = 10; // hard coded to menu id
	/**   Indicate if MTree is editable                   */
	private boolean editable = false;
	/**   Indicates if is client tree                     */
	private boolean clientTree = true;
	/**   Holds root node of the tree                     */
	private MTreeNode rootNode = null;
	/**   Holds each of the leaves to be added            */
	private TreeNodeBase treeData = null;
	/**   UIParameter used to bind backing bean to page   */
	private UIParameter param;
	/**   Holds URL of website to navigate to             */
	private String url = "";
	/**   Holds <ID, Name> pair of window names           */
	private HashMap<Integer, String> windowNames = null;
	/**	  New MTree										  */
	private MTree mTree = null;
	/**   Used to keep every window number unique         */
	private int windowCount = 1;
	/**	Holds an array list of shortcuts				  */
	private HashMap<String,String> shortcutNames = new HashMap<String, String>();
	/**   Logging                                         */
	private CLogger log = CLogger.getCLogger(TreeBacker.class);
	/**   Holds value of check box on menu page			  */
	private boolean expandMenu;
	/**   True if check box on tabbedPane.jsp is clicked  */
	private boolean checkBoxWasClicked = false;
	/**	  The Node path									  */
	private String _nodePath;
	/**   Helps with life cycle issues					  */ 
	private boolean isFirstTimeThrough = true;

	/**
	 * set the HTML tree
	 * @param tree
	 */
	public void setTree(HtmlTree tree)
	{
		_tree = tree;
	}

	/**
	 * return the HTML tree
	 * @return
	 */
	public HtmlTree getTree()
	{
		return _tree;
	}

	/**
	 * set the node path
	 */
	public void setNodePath(String nodePath)
	{
		_nodePath = nodePath;
	}

	/**
	 * get the node path
	 * @return
	 */
	public String getNodePath()
	{
		return _nodePath;
	}

	/**
	 * @return the isExpanded
	 */
	public boolean getExpandMenu() {
		return expandMenu;
	}

	/**
	 * @param isExpanded the isExpanded to set
	 */
	public void setExpandMenu(boolean expandMenu) {
		this.expandMenu = expandMenu;
	}

	/**
	 * used to bind the tree2 to the treeBacker backing bean
	 * @param param
	 */
	public UIParameter getParam() {
		return param;
	}

	/**
	 * used to bind the tree2 to the treeBacker backing bean
	 * @param param
	 */
	public void setParam(UIParameter param) {
		this.param = param;
	}

	/**
	 * retrieve necessary information to set up the tree
	 * @return
	 */
	public TreeNode getTreeData()
	{
		if (windowNames == null)
		{
			getWindowNamesFromDatabase();
		}
		if (mTree == null)
		{
			// this section of code taken from org.compiere.apps.AMenu from the constructor
			int AD_Role_ID = Env.getAD_Role_ID(Env.getCtx());
			treeId = DB.getSQLValue(null,
					"SELECT COALESCE(r.AD_Tree_Menu_ID, ci.AD_Tree_Menu_ID)" 
					+ "FROM AD_ClientInfo ci" 
					+ " INNER JOIN AD_Role r ON (ci.AD_Client_ID=r.AD_Client_ID) "
					+ "WHERE AD_Role_ID=?", AD_Role_ID);
			if (treeId <= 0)
				treeId = 10;	//	Menu

			mTree = new MTree(Env.getCtx(), treeId, editable, clientTree, null);
			rootNode = mTree.getRoot();
			treeData = new TreeNodeBase("parent", rootNode.getName(), false);
			createTree(rootNode, treeData);
		}

		// if expand all is checked, and the tree isn't already expanded
		if (getExpandMenu() && checkBoxWasClicked)
		{
			checkBoxWasClicked = false;
			expandAllNodes();
		}
		// if expand all is not checked and the tree isn't already collapsed 
		if ((! getExpandMenu()) && checkBoxWasClicked)
		{
			checkBoxWasClicked = false;
			collapseAllNodes();
		}
		return treeData;
	}
	
	/**
	 * create the tree for the tree2 JSF component
	 * @param node
	 * @param treeNodeBase
	 */

	private void createTree(MTreeNode node, TreeNodeBase treeNodeBase)
	{  
		if(node.isLeaf())
		{
			//shortcuts
			if (node.isOnBar()) 
			{
				if(shortcutNames.containsKey("Shortcuts"))
				{
					shortcutNames.clear();
				}
				shortcutNames.put(node.getName(),node.getName());
			}

			if(node.isReport())
			{
				treeNodeBase.getChildren().add(new TreeNodeBase("document", node.getName(), true));
			}
			else if (node.isWindow() || node.isForm())
			{
				if (node.getAD_Window_ID() != 0)
				{
					String identifier = String.valueOf(node.getAD_Window_ID());
					treeNodeBase.getChildren().add(new TreeNodeBase("window", node.getName(), identifier, true));
				}
				else
				{
					treeNodeBase.getChildren().add(new TreeNodeBase("other", node.getName(), true));
					log.warning("AD_Window_ID was zero.  The link to " + node.getName() + " will not be made");                    
				}
			}
			else if (node.isForm())
			{
				treeNodeBase.getChildren().add(new TreeNodeBase("form", node.getName(), true));
			}
			else if (node.isProcess())
			{
				treeNodeBase.getChildren().add(new TreeNodeBase("process", node.getName(), true));
			}
			else if (node.isWorkFlow())
			{
				// Modeling the html web app, WorkFlow's aren't used in the web implementation
				//treeNodeBase.getChildren().add(new TreeNodeBase("workflow", node.getName(), true));
			}
			else if (node.isWorkbench())
			{
				// Modeling the html web app, Workbench's aren't used in the web implementation				
				// treeNodeBase.getChildren().add(new TreeNodeBase("workbench", node.getName(), true));
			}
			else // nodes that haven't been handled yet
			{
				treeNodeBase.getChildren().add(new TreeNodeBase("other", node.getName(), true));
				log.warning(node.getName() + " was not handled.  Needs to be address.");
			}

			return;
		}
		else
		{   
			TreeNodeBase parentNode = new TreeNodeBase("parent", node.getName(), false);
			treeNodeBase.getChildren().add(parentNode);

			for (int i = 0; i < node.getChildCount(); i++) 
			{
				createTree((MTreeNode)node.getChildAt(i), parentNode);
			}
		}
		return;
	}

	/**
	 * NOTE: This is just to show an alternative way of supplying tree data.  You can supply either a
	 * TreeModel or TreeNode.
	 *
	 * @return TreeModel
	 */
	public TreeModel getExpandedTreeData()
	{
		return new TreeModelBase(getTreeData());
	}
	/**
	 * expand all of the nodes in the tree
	 * @return
	 */
	public String expandAllNodes()
	{
		_tree.expandAll();
		return null;
	}

	/**
	 * collapse all the nodes in the tree
	 * @return
	 */
	public String collapseAllNodes()
	{
		_tree.collapseAll();
		return null;
	}

	/**
	 * get the window name from the windowNames hashmap
	 * @param ID
	 * @return
	 */
	public String getNameFromHashMap(Integer ID)
	{
		String name = windowNames.get(ID);
		return name; 
	}

	/**
	 * return a list of the shortcuts for the shortcut menu
	 * @return
	 */
	public HashMap<String,String> getShortcutMap()
	{
		if (shortcutNames.isEmpty())
		{
			shortcutNames.put("Shortcuts","Shortcuts");
		}
		return shortcutNames;
	}

	/**
	 * get the url for the window to navigate to.  Create when building the tree
	 * @return
	 */
	public String getUrl() {
		if (getParam().getValue() != null)
		{
			Integer key = Integer.parseInt(getParam().getValue().toString());
			String windowName = getNameFromHashMap(key);
			String[] tempNameArray = windowName.split(" ");
			for (int i = 0; i < tempNameArray.length; i++) 
			{
				if (i == 0) 
				{
					windowName = tempNameArray[i].toLowerCase();
				} 
				else 
				{
					windowName += tempNameArray[i];
				}
			}

			// url for generated window
			url = "/newInterface/window/" + windowName + ".jsf?windowNo=" + (windowCount++) + "&windowId=" + key.toString();
		}
		else
		{
			log.warning("There was an error trying to get windowId");
		}
		return url;
	}

	/**
	 * check the node path and see if it is valid
	 * @param context
	 * @param component
	 * @param value
	 */
	public void checkPath(FacesContext context, UIComponent component, java.lang.Object value)
	{
		// make sure path is valid (leaves cannot be expanded or renderer will complain)
		FacesMessage message = null;

		String[] path = _tree.getPathInformation(value.toString());

		for (int i = 0; i < path.length; i++)
		{
			String nodeId = path[i];
			try
			{
				_tree.setNodeId(nodeId);
			}
			catch (Exception e)
			{
				throw new ValidatorException(message, e);
			}

			if (_tree.getNode().isLeaf())
			{
				message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
						"Invalid node path (cannot expand a leaf): " + nodeId,
						"Invalid node path (cannot expand a leaf): " + nodeId);
				throw new ValidatorException(message);
			}
		}
	}
	/**
	 * Gets all of the window names from the database and puts them in a HashMap.  The HashMap
	 * is used to lookup the window names from the paramter 'windowId'.
	 */
	public void getWindowNamesFromDatabase()
	{
		if (isFirstTimeThrough)
		{
			windowNames = new HashMap<Integer, String>();
			String sql = "SELECT AD_Window_ID, Name FROM AD_Window WHERE IsActive='Y'";
			try 
			{
				PreparedStatement psmnt = DB.prepareStatement(sql, null);
				ResultSet rs = psmnt.executeQuery();
				while (rs.next())
				{
					windowNames.put(rs.getInt("AD_Window_ID"), rs.getString("Name"));
				}
				rs.close();
			}
			catch (SQLException sqle)
			{
				log.warning("There was an SQL exception: " + sqle.toString());
			}
			isFirstTimeThrough = false;
		}
	}
	
	/**
	 * expand a specific node path
	 * @param event
	 */
	public void expandPath(ActionEvent event)
	{
		_tree.expandPath(_tree.getPathInformation(_nodePath));
	}

	/**
	 * Called by hidden button to submit page and register a change in the checkbox
	 * on the tabbedPane.jsp page
	 * @return empty string
	 */
	public String checkBoxChanged()
	{
		checkBoxWasClicked = true;
		return "";
	}
}
